services:
  caddy:
    build: .
    container_name: caddy
    restart: unless-stopped
    environment:
      - CADDY_INGRESS_NETWORKS=caddy_network
      - TZ=America/Mexico_City
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_network
    dns:
      - 1.1.1.1
      - 1.0.0.1
    labels:
      caddy: |
        {
            dynamic_dns {
                provider cloudflare env.CLOUDFLARE_API_TOKEN
                domains {
                    bowline.im
                }
            }
            admin localhost:2019
            email env.ACME_EMAIL
            acme_dns cloudflare env.CLOUDFLARE_API_TOKEN
        }

volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config

networks:
  caddy_network:
    name: caddy_network
    external: true
