services:
  caddy:
    build: .
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    cap_add:
      # The NET_ADMIN capability allows it to override the low default limits
      # of the operating system without having to change kernel parameters via sysctl
      - NET_ADMIN
    environment:
      TZ: "America/Mexico_City"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019" # Admin API port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy-network
    # The group_add configuration in the Caddy docker-compose.yml
    # is needed because Caddy needs access to the Docker socket
    group_add:
      - "1002" # Docker group ID (verify with: getent group docker | cut -d: -f3)
    labels:
      caddy: |
        {
          email {$ACME_EMAIL}
          admin localhost:2019

          dynamic_dns {
            provider cloudflare {$CLOUDFLARE_API_TOKEN}
            domains {
              bowline.im {
                a hoard adguard
              }
            }
            check_interval 5m
            ip_source https://api.ipify.org
          }
        }
volumes:
  caddy_data:
  caddy_config:

networks:
  caddy-network:
    name: caddy_network
