services:
  caddy:
    build: .
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    cap_add:
      # The NET_ADMIN capability allows it to override the low default limits
      # of the operating system without having to change kernel parameters via sysctl
      - NET_ADMIN
    environment:
      TZ: "America/Mexico_City"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019" # Admin API port
    networks:
      - caddy-network
    # The group_add configuration in the Caddy docker-compose.yml
    # is needed because Caddy needs access to the Docker socket
    group_add:
      - "1002" # Docker group ID (verify with: getent group docker | cut -d: -f3)
    labels:
      caddy: |
        {
          admin localhost:2019
          email hola@mpz.im
          acme_dns cloudflare {$CLOUDFLARE_API_TOKEN}
        }
volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config

networks:
  caddy-network:
    name: caddy_network
