services:
  caddy:
    build: .
    container_name: caddy
    restart: unless-stopped
    environment:
      - CADDY_INGRESS_NETWORKS=caddy_network
      - TZ=America/Mexico_City
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_network
    dns:
      - 1.1.1.1
      - 1.0.0.1
    labels:
      # Global options
      caddy.admin: "localhost:2019"
      caddy.email: "${ACME_EMAIL}"

      # Dynamic DNS configuration
      caddy.dynamic_dns: ""
      caddy.dynamic_dns.provider: "cloudflare ${CLOUDFLARE_API_TOKEN}"
      caddy.dynamic_dns.domains: "@"
      caddy.dynamic_dns.zone: "bowline.im"
      caddy.dynamic_dns.check_interval: "5m"
      caddy.dynamic_dns.ip_source: "interface eth0"
      caddy.dynamic_dns.ip_source_1: "simple_http https://icanhazip.com"
      caddy.dynamic_dns.ip_source_2: "simple_http https://api64.ipify.org"
      caddy.dynamic_dns.dynamic_domains: ""

volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config

networks:
  caddy_network:
    name: caddy_network
    external: true
