services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PLEX_CLAIM: ${PLEX_CLAIM}
    networks:
      - frontend
      - plex_net
    ports:
      - "32400:32400" # Open this port on your router for external connection
    volumes:
      - plex_config:/config
      - plex_transcode:/transcode
      - ${MEDIA_SHARE}/media/tv:/media/tv
      - ${MEDIA_SHARE}/media/movies:/media/movies
    devices:
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SUBDOMAIN}.rule=Host(`${SUBDOMAIN}.bowline.im`)"
      - "traefik.http.services.${SUBDOMAIN}.loadbalancer.server.port=32400"

volumes:
  plex_config:
  plex_transcode:

networks:
  frontend:
    external: true
  plex_net:
