services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=${USER_UID:-1000}
      - USER_GID=${USER_GID:-1000}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWD=${DB_PASSWORD}
      - GITEA__server__SSH_PORT=${SSH_PORT}
      - GITEA__server__HTTP_PORT=${HTTP_PORT}
      - GITEA__server__ROOT_URL=${ROOT_URL}
      - GITEA__server__DOMAIN=${DOMAIN}
      # Enable Gitea Actions
      - GITEA__actions__ENABLED=true
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - ${DATA_PATH}/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${HTTP_PORT}:3000"
      - "${SSH_PORT}:22"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: gitea-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - ${DATA_PATH}/postgres:/var/lib/postgresql/data

  runner:
    image: gitea/act_runner:latest
    container_name: gitea-runner
    restart: unless-stopped
    depends_on:
      - gitea
    networks:
      - gitea
    volumes:
      - ${DATA_PATH}/runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yaml:/config.yaml
    environment:
      - GITEA_INSTANCE_URL=${ROOT_URL}
      # The registration token needs to be added after initial Gitea setup
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_REGISTRATION_TOKEN}
      - GITEA_RUNNER_NAME=${RUNNER_NAME:-gitea-runner}
      - CONFIG_FILE=/config.yaml

networks:
  gitea:
    external: false
