services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWD=${DB_PASSWORD}
      - GITEA__server__SSH_PORT=${SSH_PORT}
      - GITEA__server__HTTP_PORT=${HTTP_PORT}
      - GITEA__server__ROOT_URL=${ROOT_URL}
      - GITEA__server__DOMAIN=${DOMAIN}
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${HTTP_PORT}:3000"
      - "${SSH_PORT}:22"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: gitea-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  gitea:
    external: false

volumes:
  gitea_data:
    name: gitea_data
  postgres_data:
    name: postgres_data
