services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
