services:
  woodpecker-server:
    container_name: woodpecker-server
    image: woodpeckerci/woodpecker-server:v3
    ports:
      - 8000:8000
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=https://${SUBDOMAIN}.bowline.im
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_FORGEJO_URL=${WOODPECKER_FORGEJO_URL}
      - WOODPECKER_FORGEJO=true
      - WOODPECKER_FORGEJO_CLIENT=${WOODPECKER_FORGEJO_CLIENT}
      - WOODPECKER_FORGEJO_SECRET=${WOODPECKER_FORGEJO_SECRET}
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}/server:/var/lib/woodpecker/
    networks:
      - woodpecker
      - backend
      - frontend
    labels:
      - "traefik.enable=true"
      # HTTP service
      - "traefik.http.routers.woodpecker-http.rule=Host(`${SUBDOMAIN}.bowline.im`)"
      - "traefik.http.routers.woodpecker-http.service=woodpecker-http"
      - "traefik.http.routers.woodpecker-http.tls=true"
      - "traefik.http.routers.woodpecker-http.entrypoints=websecure"
      - "traefik.http.services.woodpecker-http.loadbalancer.server.port=8000"

      # gRPC service
      - "traefik.http.routers.woodpecker-grpc.rule=Host(`${SUBDOMAIN}-grpc.bowline.im`)"
      - "traefik.http.routers.woodpecker-grpc.service=woodpecker-grpc"
      - "traefik.http.routers.woodpecker-grpc.tls=true"
      - "traefik.http.routers.woodpecker-grpc.entrypoints=websecure"
      - "traefik.http.services.woodpecker-grpc.loadbalancer.server.port=9000"
      - "traefik.http.services.woodpecker-grpc.loadbalancer.server.scheme=h2c"

  woodpecker-agent:
    container_name: woodpecker-agent
    image: woodpeckerci/woodpecker-agent:v3
    restart: unless-stopped
    command: agent
    depends_on:
      - woodpecker-server
    volumes:
      - ${CONFIG_PATH}/agent:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_BACKEND_DOCKER_NETWORK=backend
    networks:
      - woodpecker
      - backend

networks:
  woodpecker:
  frontend:
    external: true
  backend:
    external: true
