services:
  mcp:
    image: python:3.11-slim
    container_name: mcp
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "
      apt-get update && apt-get install -y curl &&
      pip install mcpo uv &&
      uvx mcpo --host 0.0.0.0 --port 8000 -- uvx mcp-server-time --local-timezone=${TZ:-America/New_York}
      "
    environment:
      - TZ=${TZ:-America/New_York}
    volumes:
      - ./data:/root/.cache
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  backend:
    external: true